module UsersHelper
      def gravatar_for(user, size)
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase) #a unique id is created for the user object by using their email address and feeding it to a hash function (MD5)
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}" #a url is generated by using the unique id
     image_tag(gravatar_url, alt: user.name, class: "gravatar", :style => "width: #{size}px") #an image is retrieved from the generated url and displayed using the image_tag helper. 
  end
end
